root: true
parserOptions:
  project: './tsconfig.json'
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  'no-constant-condition': 0
  '@typescript-eslint/no-floating-promises': 2
  'no-underscore-dangle': 0
  '@typescript-eslint/dot-notation': 0
  camelcase:
  - error
  curly:
  - error
  import/prefer-default-export: 0
  import/no-extraneous-dependencies:
  - error
  - devDependencies:
    - "**/*.test.ts"
    - "**/*.spec.ts"
    - "**/*.test.tsx"
    - "**/*.spec.tsx"
    - "**/*.helper.ts"
    - "**/jest-setup.ts"
overrides:
  - files:
    - "**/*.interface.ts"
    - "**/*.entity.ts"
    - "**/*.entity.tsx"
    - "**/*.schema.ts"
    - "**/*.schema.tsx"
    - "**/*.type.ts"
    - "**/*.type.tsx"
    - "**/*.repository.ts"
    - "**/*.repository.tsx"
    rules:
      camelcase: 0
      '@typescript-eslint/naming-convention':
        - error
        - selector: property
          format:
          - snake_case
          - camelCase
          - UPPER_CASE
