services:
  app:
    build:
      context: .
    container_name: waving-test
    networks:
      - main
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/waving-test
    ports:
      - "3000:3000"
      - "9229:9229"
    develop:
      watch:
        - path: .
          action: rebuild
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:15
    container_name: waving-test-db
    networks:
      - main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: waving-test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  main:
    external: true

volumes:
  postgres_data:
